language: elixir
sudo: false
elixir: 1.4.4
otp_release: 19.1
notifications:
  recipients:
    - fredrik.enestad@soundtrackyourbrand.com
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
